import stylistic from '@stylistic/eslint-plugin'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import react from 'eslint-plugin-react'
import perfectionist from 'eslint-plugin-perfectionist'

export default [
    {
        files: ['**/*.{ts,tsx,js,jsx}'],
        languageOptions: {
            globals: {
                Bun: 'readonly',
                console: 'readonly',
                document: 'readonly',
                fetch: 'readonly',
                setTimeout: 'readonly',
                WebSocket: 'readonly',
                window: 'readonly',
            },
            parser: tsparser,
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                },
                ecmaVersion: 'latest',
                sourceType: 'module',
            },
        },
        plugins: {
            '@stylistic': stylistic,
            '@typescript-eslint': tseslint,
            perfectionist: perfectionist,
            react: react,
        },
        rules: {
            '@stylistic/array-bracket-newline': ['error', 'consistent'],
            '@stylistic/array-bracket-spacing': ['error', 'never'],
            '@stylistic/array-element-newline': ['error', 'consistent'],
            '@stylistic/arrow-parens': ['error', 'always'],
            '@stylistic/arrow-spacing': ['error', {after: true, before: true}],
            '@stylistic/block-spacing': ['error', 'never'],
            '@stylistic/brace-style': ['error', '1tbs'],
            '@stylistic/comma-dangle': ['error', 'always-multiline'],
            '@stylistic/comma-spacing': ['error', {after: true, before: false}],
            '@stylistic/comma-style': ['error', 'last'],
            '@stylistic/computed-property-spacing': ['error', 'never'],
            '@stylistic/dot-location': ['error', 'property'],
            '@stylistic/eol-last': ['error', 'always'],
            '@stylistic/function-call-argument-newline': ['error', 'consistent'],
            '@stylistic/function-call-spacing': ['error', 'never'],
            '@stylistic/function-paren-newline': ['error', 'consistent'],
            '@stylistic/generator-star-spacing': ['error', {after: true, before: false}],
            '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
            '@stylistic/indent': ['error', 4, {
                ArrayExpression: 1,
                CallExpression: {arguments: 1},
                flatTernaryExpressions: false,
                FunctionDeclaration: {body: 1, parameters: 1},
                FunctionExpression: {body: 1, parameters: 1},
                ignoredNodes: [
                    'TemplateLiteral *',
                    'JSXElement',
                    'JSXElement > *',
                    'JSXAttribute',
                    'JSXIdentifier',
                    'JSXNamespacedName',
                    'JSXMemberExpression',
                    'JSXSpreadAttribute',
                    'JSXExpressionContainer',
                    'JSXOpeningElement',
                    'JSXClosingElement',
                    'JSXFragment',
                    'JSXOpeningFragment',
                    'JSXClosingFragment',
                    'JSXText',
                    'JSXEmptyExpression',
                    'JSXSpreadChild',
                    'TSTypeParameterInstantiation',
                    'FunctionExpression > .params[decorators.length > 0]',
                    'FunctionExpression > .params[decorators.length > 0] > .params',
                    'ClassBody.body > PropertyDefinition[decorators.length > 0]',
                ],
                ImportDeclaration: 1,
                MemberExpression: 1,
                ObjectExpression: 1,
                offsetTernaryExpressions: true,
                outerIIFEBody: 1,
                SwitchCase: 1,
                VariableDeclarator: 1,
            }],
            '@stylistic/indent-binary-ops': ['error', 4],
            // ===== JSX Rules =====
            '@stylistic/jsx-child-element-spacing': 'off',
            '@stylistic/jsx-closing-bracket-location': ['error', 'line-aligned'],
            '@stylistic/jsx-closing-tag-location': ['error', 'line-aligned'],
            '@stylistic/jsx-curly-brace-presence': ['error', {children: 'never', props: 'never'}],
            '@stylistic/jsx-curly-newline': ['error', {multiline: 'consistent', singleline: 'consistent'}],
            '@stylistic/jsx-curly-spacing': ['error', {children: true, when: 'never'}],
            '@stylistic/jsx-equals-spacing': ['error', 'never'],
            '@stylistic/jsx-first-prop-new-line': ['error', 'multiline-multiprop'],
            '@stylistic/jsx-function-call-newline': ['error', 'multiline'],
            '@stylistic/jsx-indent-props': ['error', 4],
            '@stylistic/jsx-max-props-per-line': ['error', {maximum: 1, when: 'multiline'}],
            '@stylistic/jsx-newline': 'off',
            '@stylistic/jsx-pascal-case': ['error'],
            '@stylistic/jsx-quotes': ['error', 'prefer-single'],
            '@stylistic/jsx-self-closing-comp': ['error', {
                component: true,
                html: true,
            }],

            '@stylistic/jsx-sort-props': ['error', {ignoreCase: true}],
            '@stylistic/jsx-tag-spacing': ['error', {
                afterOpening: 'never',
                beforeClosing: 'never',
                beforeSelfClosing: 'always',
                closingSlash: 'never',
            }],
            '@stylistic/key-spacing': ['error', {afterColon: true, beforeColon: false}],
            '@stylistic/keyword-spacing': ['error', {after: true, before: true}],
            '@stylistic/line-comment-position': ['error', {position: 'above'}],
            '@stylistic/linebreak-style': ['error', 'unix'],
            '@stylistic/lines-around-comment': ['error', {
                afterBlockComment: false,
                afterLineComment: false,
                allowArrayEnd: true,
                allowArrayStart: true,
                allowBlockEnd: true,
                allowBlockStart: true,
                allowObjectEnd: true,
                allowObjectStart: true,
                beforeBlockComment: true,
                beforeLineComment: false,
            }],
            '@stylistic/lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: false}],
            '@stylistic/max-len': ['error', 130],
            '@stylistic/max-statements-per-line': ['error', {max: 1}],
            '@stylistic/member-delimiter-style': ['error', {
                multiline: {
                    delimiter: 'none',
                },
                singleline: {
                    delimiter: 'semi',
                    requireLast: false,
                },
            }],
            '@stylistic/multiline-comment-style': ['error', 'starred-block'],
            '@stylistic/multiline-ternary': ['error', 'always-multiline'],
            '@stylistic/new-parens': ['error', 'always'],
            '@stylistic/newline-per-chained-call': ['error', {ignoreChainWithDepth: 3}],
            '@stylistic/no-confusing-arrow': ['error', {allowParens: true}],
            '@stylistic/no-extra-parens': ['error', 'all', {
                nestedBinaryExpressions: false,
                returnAssign: false,
            }],
            '@stylistic/no-extra-semi': ['error'],
            '@stylistic/no-floating-decimal': ['error'],
            '@stylistic/no-mixed-operators': ['error', {
                allowSamePrecedence: true,
                groups: [
                    ['+', '-', '*', '/', '%', '**'],
                    ['&', '|', '^', '~', '<<', '>>', '>>>'],
                    ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                    ['&&', '||'],
                    ['in', 'instanceof'],
                ],
            }],
            '@stylistic/no-mixed-spaces-and-tabs': ['error'],
            '@stylistic/no-multi-spaces': ['error', {
                ignoreEOLComments: false,
            }],
            '@stylistic/no-multiple-empty-lines': ['error', {max: 2, maxBOF: 0, maxEOF: 1}],
            '@stylistic/no-tabs': ['error'],
            '@stylistic/no-trailing-spaces': ['error', {
                ignoreComments: false,
                skipBlankLines: false,
            }],
            '@stylistic/no-whitespace-before-property': ['error'],
            '@stylistic/nonblock-statement-body-position': ['error', 'beside', {overrides: {}}],
            '@stylistic/object-curly-newline': ['error', {consistent: true, multiline: true}],
            '@stylistic/object-curly-spacing': ['error', 'never'],
            '@stylistic/object-property-newline': ['error', {allowAllPropertiesOnSameLine: true}],
            '@stylistic/one-var-declaration-per-line': ['error', 'always'],
            '@stylistic/operator-linebreak': ['error', 'after'],
            '@stylistic/padded-blocks': ['error', 'never'],

            '@stylistic/padding-line-between-statements': 'off',

            '@stylistic/quote-props': ['error', 'as-needed'],
            // ===== Quote Rules =====
            '@stylistic/quotes': ['error', 'single', {avoidEscape: true}],
            '@stylistic/rest-spread-spacing': ['error', 'never'],
            // ===== Semicolon Rules =====
            '@stylistic/semi': ['error', 'never'],
            '@stylistic/semi-spacing': ['error', {after: true, before: false}],
            '@stylistic/semi-style': ['error', 'last'],
            '@stylistic/space-before-blocks': ['error', 'always'],
            '@stylistic/space-before-function-paren': ['error', 'never'],
            '@stylistic/space-in-parens': ['error', 'never'],

            '@stylistic/space-infix-ops': ['error'],

            '@stylistic/space-unary-ops': ['error', {nonwords: false, words: true}],
            '@stylistic/spaced-comment': ['error', 'always', {
                block: {balanced: true, exceptions: ['*'], markers: ['!']},
                line: {exceptions: ['-', '+'], markers: ['/']},
            }],

            '@stylistic/switch-colon-spacing': ['error', {after: true, before: false}],
            '@stylistic/template-curly-spacing': ['error', 'never'],
            // ===== Misc Rules =====
            '@stylistic/template-tag-spacing': ['error', 'never'],
            '@stylistic/type-annotation-spacing': ['error'],
            '@stylistic/type-generic-spacing': ['error'],
            '@stylistic/type-named-tuple-spacing': ['error'],

            '@stylistic/wrap-iife': ['error', 'inside'],

            '@stylistic/wrap-regex': 'off',
            '@stylistic/yield-star-spacing': ['error', {after: true, before: false}],
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': ['warn', {
                argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_',
            }],
            'perfectionist/sort-interfaces': ['error', {
                ignoreCase: true,
                order: 'asc',
                type: 'natural',
            }],
            'perfectionist/sort-object-types': ['error', {
                ignoreCase: true,
                order: 'asc',
                type: 'natural',
            }],
            // Sorting rules (auto-fixable)
            'perfectionist/sort-objects': ['error', {
                ignoreCase: true,
                order: 'asc',
                type: 'natural',
            }],

            'react/prop-types': 'off',
            'react/react-in-jsx-scope': 'off',
        },
        settings: {
            react: {
                pragma: 'h',
                version: '18.0',
            },
        },
    },
]
