import {extractWorkspacePackages, isApplicationPackage, findWorkspaceRoot} from '../workspace'

/**
 * Generate nginx configuration for all packages
 */
export function generateNginx(domain: string): string {
    const workspaceRoot = findWorkspaceRoot() || process.cwd()
    const packages = extractWorkspacePackages(workspaceRoot)
    const appPackages = packages.filter(pkg => isApplicationPackage(pkg))

    // Port assignments
    const ports: Record<string, number> = {
        'malkovich': 3032,
        'expressio': 3030,
        'pyrite': 3031,
    }

    let config = `# Nginx configuration for ${domain}\n`
    config += `# Generated by malkovich generate-nginx --domain ${domain}\n\n`

    // HTTP to HTTPS redirect for main domain
    config += `# HTTP to HTTPS redirect\n`
    config += `server {\n`
    config += `    listen 80;\n`
    config += `    server_name ${domain} www.${domain};\n`
    config += `    return 301 https://$server_name$request_uri;\n`
    config += `}\n\n`

    // HTTPS server for main domain (malkovich)
    config += `# HTTPS server - Main domain (malkovich)\n`
    config += `server {\n`
    config += `    listen 443 ssl;\n`
    config += `    http2 on;\n`
    config += `    server_name ${domain} www.${domain};\n\n`
    config += `    # SSL certificates (Let's Encrypt)\n`
    config += `    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;\n`
    config += `    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;\n\n`
    config += `    # SSL configuration\n`
    config += `    ssl_protocols TLSv1.2 TLSv1.3;\n`
    config += `    ssl_ciphers HIGH:!aNULL:!MD5;\n`
    config += `    ssl_prefer_server_ciphers on;\n`
    config += `    ssl_session_cache shared:SSL:10m;\n`
    config += `    ssl_session_timeout 10m;\n\n`
    config += `    # Webhook endpoint\n`
    config += `    location /webhook {\n`
    config += `        proxy_pass http://localhost:${ports['malkovich']};\n`
    config += `        proxy_http_version 1.1;\n`
    config += `        proxy_set_header Host $host;\n`
    config += `        proxy_set_header X-Real-IP $remote_addr;\n`
    config += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`
    config += `        proxy_set_header X-Forwarded-Proto $scheme;\n\n`
    config += `        # Increase timeouts for deployment\n`
    config += `        proxy_connect_timeout 60s;\n`
    config += `        proxy_send_timeout 60s;\n`
    config += `        proxy_read_timeout 60s;\n`
    config += `    }\n\n`
    config += `    # All other routes to malkovich\n`
    config += `    location / {\n`
    config += `        proxy_pass http://localhost:${ports['malkovich']};\n`
    config += `        proxy_http_version 1.1;\n`
    config += `        proxy_set_header Host $host;\n`
    config += `        proxy_set_header X-Real-IP $remote_addr;\n`
    config += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`
    config += `        proxy_set_header X-Forwarded-Proto $scheme;\n`
    config += `    }\n`
    config += `}\n\n`

    // Generate subdomain configs for application packages
    for (const pkg of appPackages) {
        const port = ports[pkg] || 3030 + appPackages.indexOf(pkg)
        const subdomain = `${pkg}.${domain}`

        config += `# ${pkg} service (subdomain: ${subdomain})\n`
        config += `server {\n`
        config += `    listen 80;\n`
        config += `    server_name ${subdomain};\n`
        config += `    return 301 https://$server_name$request_uri;\n`
        config += `}\n\n`

        config += `server {\n`
        config += `    listen 443 ssl;\n`
        config += `    http2 on;\n`
        config += `    server_name ${subdomain};\n\n`
        config += `    # SSL certificates (Let's Encrypt)\n`
        config += `    ssl_certificate /etc/letsencrypt/live/${subdomain}/fullchain.pem;\n`
        config += `    ssl_certificate_key /etc/letsencrypt/live/${subdomain}/privkey.pem;\n\n`
        config += `    # SSL configuration\n`
        config += `    ssl_protocols TLSv1.2 TLSv1.3;\n`
        config += `    ssl_ciphers HIGH:!aNULL:!MD5;\n`
        config += `    ssl_prefer_server_ciphers on;\n`
        config += `    ssl_session_cache shared:SSL:10m;\n`
        config += `    ssl_session_timeout 10m;\n\n`
        config += `    location / {\n`
        config += `        proxy_pass http://localhost:${port};\n`
        config += `        proxy_http_version 1.1;\n`
        config += `        proxy_set_header Host $host;\n`
        config += `        proxy_set_header X-Real-IP $remote_addr;\n`
        config += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`
        config += `        proxy_set_header X-Forwarded-Proto $scheme;\n`
        config += `    }\n`
        config += `}\n\n`
    }

    return config
}
