import {extractWorkspacePackages, isApplicationPackage, findWorkspaceRoot} from '../workspace'
import {join} from 'path'

/**
 * Generate systemd service file for a package
 */
function generateServiceFile(packageName: string, domain: string, port: number): string {
    const serviceName = packageName
    const workingDir = `/home/garage44/garage44/packages/${packageName}`

    return `[Unit]
Description=${packageName} service
After=network.target

[Service]
Type=simple
User=garage44
Group=garage44
WorkingDirectory=${workingDir}
Environment="NODE_ENV=production"
Environment="BUN_ENV=production"
Environment="PATH=/home/garage44/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=/home/garage44/.bun/bin/bun run server -- --port ${port}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
`
}

/**
 * Generate systemd service files for all packages
 */
export function generateSystemd(domain: string): string {
    const workspaceRoot = findWorkspaceRoot() || process.cwd()
    const packages = extractWorkspacePackages(workspaceRoot)
    const appPackages = packages.filter(pkg => isApplicationPackage(pkg))

    // Port assignments
    const ports: Record<string, number> = {
        'malkovich': 3032,
        'expressio': 3030,
        'pyrite': 3031,
    }

    let output = `# Systemd service files for ${domain}\n`
    output += `# Generated by malkovich generate-systemd --domain ${domain}\n\n`

    // Generate malkovich service (main domain)
    output += `# Malkovich service (main domain: ${domain})\n`
    output += generateServiceFile('malkovich', domain, ports['malkovich'])
    output += '\n'

    // Generate services for application packages
    for (const pkg of appPackages) {
        const port = ports[pkg] || 3030 + appPackages.indexOf(pkg)
        output += `# ${pkg} service (subdomain: ${pkg}.${domain})\n`
        output += generateServiceFile(pkg, domain, port)
        output += '\n'
    }

    return output
}
